--CREATE DATABASE
CREATE DATABASE AZURE_DB
USE AZURE_DB

--CREATE TABLE
CREATE TABLE EMPLOYEES 
(EMP_ID INT,
EMP_NAME VARCHAR(30),
)

SELECT * FROM EMPLOYEES

--INSERT VALUES INTO TABLE
INSERT INTO EMPLOYEES (EMP_ID,EMP_NAME) VALUES
(1, 'RAHUL'),
(2, 'AJAY'),
(3,'AJITH')

--ADD NEW COLUMNS
ALTER TABLE EMPLOYEES
ADD SALARY INT 

ALTER TABLE EMPLOYEES
ADD CITY VARCHAR(20), STATES VARCHAR(30)	

INSERT INTO EMPLOYEES(EMP_ID,EMP_NAME,SALARY,CITY,STATES) VALUES
(1, 'RAHUL', 50000, 'CHENNAI', 'TAMILNADU'),
(2, 'AJAY', 60000, 'BANGALORE', 'KARNATAKA'),
(3, 'AJITH',70000, 'HYDERABAD', 'TELENGANA')

SELECT * INTO EMPLOYEES_NEW FROM EMPLOYEES
DROP TABLE EMPLOYEES_NEW
SELECT * FROM EMPLOYEES_NEW

--UPDATE 
UPDATE EMPLOYEES SET EMP_NAME='RAVI'
WHERE EMP_ID=2

UPDATE EMPLOYEES SET SALARY=85000
WHERE EMP_NAME='AJITH'

INSERT INTO EMPLOYEES(EMP_ID,EMP_NAME,SALARY,CITY,STATES) VALUES 
(4,'MEGHNA',80000,'PATNA','BIHAR')

INSERT INTO EMPLOYEES(EMP_ID,EMP_NAME,SALARY,CITY,STATES) VALUES
(5,'RASHID',90000,'TRICHY','TAMILNADU'),
(6,'RAHMAN',100000,'COCHIN','KERALAM'),
(7,'NISHA',30000,'KANNUR','KERALAM'),
(8,'ASHWIN',45000,'TRIVANDRUM','KERALAM')

--DELETE
DELETE FROM EMPLOYEES_NEW
WHERE EMP_ID=3

-- TRUNCATE
TRUNCATE TABLE EMPLOYEES

--DROP
DROP TABLE EMPLOYEES
