USE AZURE_DB

SELECT*FROM ORDERS

SELECT * FROM ECOMMERCE
-- Display the Order Date along with the Year.

SELECT ORDER_DATE, YEAR(ORDER_DATE) AS YEAR 
FROM ECOMMERCE

-- Display the Month Name.

SELECT ORDER_DATE, MONTH(ORDER_DATE) AS MONTH FROM ECOMMERCE

SELECT ORDER_DATE, DATENAME(MONTH,ORDER_DATE) AS MONTH_NAME 
FROM ECOMMERCE

SELECT ORDER_DATE, DATEPART(MONTH,ORDER_DATE) AS MONTH_NUMBER
FROM ECOMMERCE

--Display Day of Month

SELECT ORDER_DATE, DAY(ORDER_DATE) AS DAY
FROM ECOMMERCE

--Display Weekday Name
SELECT ORDER_DATE, DATENAME(WEEKDAY,ORDER_DATE) AS WEEKDAY_NAME
FROM ECOMMERCE

--Display Weekday Number

SELECT ORDER_DATE, DATEPART(WEEKDAY,ORDER_DATE) AS WEEKDAY_NUMBER
FROM ECOMMERCE

--Display Quarter number
SELECT ORDER_DATE, DATEPART(QUARTER,ORDER_DATE) AS QUARTER_NUMBER
FROM ECOMMERCE

--Display Week Number
SELECT ORDER_DATE, DATEPART(WEEK,ORDER_DATE) AS WEEK_NUMBER
FROM ECOMMERCE

--Calculate shipping days
SELECT DATEDIFF(DAY, [ORDER DATE], [SHIP DATE]) AS SHIPPING_DAYS
FROM ORDERS

--Find orders delivered in more than 10 days.
SELECT [ORDER ID], [CUSTOMER ID]
FROM ORDERS
WHERE DATEDIFF(DAY, [ORDER DATE], [SHIP DATE]) > '10'


--Average shipping time, Maxmium Shipping, Minimum Shipping Time
SELECT AVG(DATEDIFF(DAY,[ORDER DATE],[SHIP DATE])) AS AVERAGE_SHIPPING_TIME,
MAX(DATEDIFF(DAY,[ORDER DATE],[SHIP DATE])) AS MAX_SHIPPING_TIME,
MIN(DATEDIFF(DAY,[ORDER DATE],[SHIP DATE])) AS MIN_SHIPPING_TIME
FROM ORDERS

--Display today's date
SELECT GETDATE() AS TODAYS_DATE

--How many days ago was each order placed?
SELECT DATEDIFF(DAY,[ORDER DATE],GETDATE()) AS DAYS_OLD
FROM ORDERS

--Orders placed in the last 365 days.
SELECT ORDER_ID
FROM ECOMMERCE
WHERE ORDER_DATE >= DATEADD(YEAR,-1,ORDER_DATE)

----Find the date expected delivery date after 1 month of order

SELECT ORDER_DATE, DATEADD(DAY,7,ORDER_DATE) AS EDD
FROM ECOMMERCE

--Find the  date after 1 month of order
SELECT ORDER_DATE, DATEADD(MONTH,1,ORDER_DATE) AS MONTHAFTERORDER
FROM ECOMMERCE

--What is the last day of order month?
SELECT ORDER_DATE,EOMONTH(ORDER_DATE) FROM ECOMMERCE

-- What are the number of days remaining in the month?
SELECT ORDER_DATE, DATEDIFF(DAY,ORDER_DATE,EOMONTH(ORDER_DATE)) 
FROM ECOMMERCE

SELECT FORMAT(Order_Date,'dd-MM-yyyy')
FROM ECOMMERCE;

SP_HELP ECOMMERCE

SELECT DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME='ECOMMERCE'

SELECT FORMAT(CAST(ORDER_DATE AS DATE),'MM-dd-yyyy')
FROM ECOMMERCE

ALTER TABLE ECOMMERCE
ALTER COLUMN ORDER_DATE DATE

--Total Sales by Month

SELECT MONTH(ORDER_DATE) AS MONTH,SUM(SALES) AS TOTAL_SALES
FROM ECOMMERCE
GROUP BY MONTH(ORDER_DATE)
ORDER BY TOTAL_SALES DESC

--Total Sales by Year
SELECT YEAR(ORDER_DATE) AS YEAR, SUM(SALES) AS TOTAL_SALES_BY_YEAR
FROM ECOMMERCE
GROUP BY YEAR(ORDER_DATE)
ORDER BY YEAR

SELECT DATEPART(QUARTER,ORDER_DATE) AS QUARTER,SUM(SALES) AS TOTAL_SALES_PER_QUARTER
FROM ECOMMERCE
GROUP BY DATEPART(QUARTER,ORDER_DATE)
ORDER BY QUARTER

--Count orders by weekday
SELECT DATENAME(WEEKDAY, ORDER_DATE) AS WEEK_, COUNT(ORDER_ID) AS TOTAL_ORDERS
FROM ECOMMERCE
GROUP BY DATENAME(WEEKDAY, ORDER_DATE)

--Find the customers who placed orders in 2023 and from which city
SELECT ORDER_ID,DATEPART(YEAR,ORDER_DATE) AS YEAR,CUSTOMER_NAME
FROM ECOMMERCE
WHERE YEAR(ORDER_DATE)='2023'

--Find the customers who placed orders in Jan
SELECT ORDER_ID,
DATENAME(MONTH,(ORDER_DATE)) AS MONTH_,CUSTOMER_NAME
FROM ECOMMERCE
WHERE MONTH(ORDER_DATE)='5'

--Which month generated the highest sales?
SELECT TOP 1 DATENAME(MONTH,ORDER_DATE) AS MONTH_NAME,
MONTH(ORDER_DATE) AS MONTH,
SUM(SALES) AS TOTAL_SALES
FROM ECOMMERCE
GROUP BY DATENAME(MONTH,ORDER_DATE), MONTH(ORDER_DATE)
ORDER BY TOTAL_SALES DESC

--Which quarter generated the highest sales?
SELECT DATEPART(QUARTER,ORDER_DATE) AS QUARTER, SUM(SALES) AS TOTAL_SALES
FROM ECOMMERCE
GROUP BY DATEPART(QUARTER,ORDER_DATE)
ORDER BY TOTAL_SALES DESC

SELECT TOP 1 DATENAME(WEEKDAY,ORDER_dATE) AS WEEKDAY,COUNT(ORDER_ID) AS TOTAL_ORDERS
FROM ECOMMERCE
GROUP BY DATENAME(WEEKDAY,ORDER_dATE)
ORDER BY TOTAL_ORDERS DESC

--Calculate Average shipping time by Region
SELECT REGION, AVG(DATEDIFF(DAY,[ORDER DATE], [SHIP DATE])) AS AVG_SHIPPING_TIME
FROM ORDERS
GROUP BY REGION
ORDER BY AVG_SHIPPING_TIME DESC

--Calculate Average shipping time by category

SELECT CATEGORY, AVG(DATEDIFF(DAY,[ORDER DATE], [SHIP DATE])) AS AVG_SHIPPING_TIME
FROM ORDERS
GROUP BY CATEGORY
ORDER BY AVG_SHIPPING_TIME DESC

--Customers with the longest shipping delay
SELECT TOP 10 [CUSTOMER ID], DATEDIFF(DAY,[ORDER DATE], [SHIP DATE]) AS AVG_SHIPPING_TIME
FROM ORDERS
GROUP BY [CUSTOMER ID]
ORDER BY DATEDIFF(DAY,[ORDER DATE], [SHIP DATE]) DESC

-- Find the customers who received the order on the same day 
SELECT TOP 10 [ORDER ID], [CUSTOMER ID], CATEGORY,[SUB-CATEGORY]
FROM ORDERS
WHERE [ORDER DATE]=[SHIP DATE]

