USE AZURE_DB

SELECT * FROM ORDERS

--STRING FUNCTIONS

--CONCAT ADDS TWO OR MORE STRINGS TOGETHER
SELECT [CUSTOMER NAME], [COUNTRY/REGION] FROM ORDERS

SELECT [CUSTOMER NAME], [COUNTRY/REGION],CONCAT([CUSTOMER NAME], ' is from ' ,[COUNTRY/REGION], ' travelled in ',[SHIP MODE]) as NAME_COUNTRY FROM ORDERS

--WSCONCAT ADDS TWO OR MORE STRINGS TOGETHER WITH A SEPARATOR 

SELECT [CUSTOMER NAME], [COUNTRY/REGION],CONCAT_WS(' is from ', [CUSTOMER NAME],[COUNTRY/REGION]) AS NAME_COUNTRY FROM ORDERS

--LEFT FUNCTION GIVES THE NUMBER OF LETTERS FROM LEFT
SELECT [CUSTOMER NAME], LEFT([CUSTOMER NAME],5) AS FIRST_4 FROM ORDERS

--RIGHT FUNCTION GIVES THE NUMBER OF LETTERS FROM RIGHT
SELECT [CUSTOMER NAME], RIGHT([CUSTOMER NAME],5) AS LAST_4 FROM ORDERS

--SUBSTRING FUNCTION GIVES THE NUMBER OF LETTERS IN THE MIDDLE
SELECT [CUSTOMER NAME], SUBSTRING([CUSTOMER NAME],5) AS MIDDLE_4 FROM ORDERS

--LENGTH GIVES THE LENGTH OF CHARACTERS
SELECT [CUSTOMER NAME], LEN([CUSTOMER NAME]) AS CHARACTER_COUNT FROM ORDERS

--LOWER FUNCTIONS CONVERTS THE STRING IN LOWER CASE
SELECT [CUSTOMER NAME], LOWER([CUSTOMER NAME]) AS LC FROM ORDERS
	
--UPPER FUNCTIONS CONVERTS THE STRING IN UPPER CASE
SELECT [CUSTOMER NAME], UPPER([CUSTOMER NAME]) AS UC FROM ORDERS

--LTRIM FUNCTION REMOVES THE SPACES FROM LEFT
SELECT LTRIM('      SAFA     ') AS  LTRIM

--RTRIM FUNCTION REMOVES THE SPACES FROM RIGHT
SELECT RTRIM('      SAFA     ') AS  RTRIM

--TRIM FUNCTION REMOVES THE SPACES BOTH LEFT AND RIGHT
SELECT TRIM('      SAFA     ') AS  TRIM

--REPLACE IS USED TO REPLACE ALL OCCURRENCES OF A SUBSTRING WITHIN A STRING WITH A NEW SUBSTRING
SELECT REGION, REPLACE(REGION,'CENTRAL','NORTH CENTRAL') AS REPLACE FROM ORDERS

SELECT REPLACE ('SQL CLASS', 'C','G')

SELECT PATINDEX ('%KAIZEN%','WWW.KAIZENKNOWLEDGE.ORG')

--PATINDEX GIVES THE INDEX OF THAT PARTICULAR CHARACTER
--%D%--CHARACTER CAN BE ANYWHERE
--D% -- IT WILL IDENTIFY THE LETTER STARTING WITH D
--%D -- IT WILL IDENTIFY THE LETTER ENDING WITH D

SELECT [CUSTOMER NAME], PATINDEX('%D%',[CUSTOMER NAME]) AS CUS_NAME_WITH_D FROM ORDERS

SELECT [CUSTOMER NAME], PATINDEX('D%',[CUSTOMER NAME]) AS CUS_NAME_WITH_D FROM ORDERS

SELECT [CUSTOMER NAME], PATINDEX('%D',[CUSTOMER NAME]) AS CUS_NAME_WITH_D FROM ORDERS

SELECT [CUSTOMER NAME],
	PATINDEX('%D%',[CUSTOMER NAME]) AS D_ANYWHERE,
	PATINDEX('D%',[CUSTOMER NAME]) AS STARTING_WITH_D,
	PATINDEX('%D',[CUSTOMER NAME]) AS ENDING_WITH_D
FROM ORDERS

